### ISSUE TITLE
Stale OSDU schema source

### ISSUE THREAD

**Issue by gehtho** [Accenture/OSDU-Ontology#1]
I saw recent activity - I am publishing the OSDU schemas for each milestone. The URL mentioned in the README is a copy. 

* The resources in that copy are based on local file references instead of schema ids
* The [resources to register the schemas in the OSDU core Schema service](https://community.opengroup.org/osdu/data/data-definitions/-/tree/master/SchemaRegistrationResources/shared-schemas/osdu) might be better, and reflect the latest version.
* OSDU treats `"status": "PUBLISHED"` as read-only. As a consequence, there are a growing number of higher minor or patch schemas - for the ontology, I would assume only the latest version should be used. Such a list of the latest versions is available in [reports](https://community.opengroup.org/osdu/data/data-definitions/-/blob/master/E-R/README.md#list-of-documented-entities), but could be generated as another artefact, easy to consume by the ontology creator.

If you are interested in a collaboration, please submit an issue on the [public OSDU GitLab](https://community.opengroup.org/osdu/data/data-definitions/-/issues) and assign it to me (Thomas Gehrmann [slb] @gehrmann).

**Comment by neda-abolhassani** [comment]
I appreciate you telling us about the best resource to use, Thomas. The README indicates that the current version of the ontology is based on the 3rd release of OSDU. On the next version of the ontology, the code will be updated based on the given resource, and the README will refer to the new resource. Upon receiving your approval, I will submit a request for sharing this work on the OSDU GitLab.

**Comment by gehtho** [comment]
Thanks for the feedback - I wonder what 'knowledge' we can inject from the schema generation perspective. I don't think you need my approval, assuming that this work here is under a OSDU compatible license.
