### ISSUE TITLE
property naming convention

### ISSUE THREAD

**Issue by VladimirAlexiev** [Accenture/OSDU-Ontology#10]
There are many properties that don't conform to the `lowerCamelCase` convention, eg:
```
totalcostamount
costcurrency
```

**Comment by VladimirAlexiev** [comment]
Furthermore, some properties are in plural, eg 
```
agreementIDs
businessActivities
```
But all props should be in singular (in RDF, any property may have multiple values, and yet each value is a single object).

**Comment by VladimirAlexiev** [comment]
The problem with lowercased props is more serious: 
All prop names are lowercased (mistyped) in Restrictions, and therefore don't match the declared property names.
For example:
```ttl
osdu:Cost rdf:type owl:Class ;
	rdfs:subClassOf [
		a owl:Restriction ;
		owl:onProperty osdu:totalcostamount ;
		owl:minCardinality "1"^^xsd:nonNegativeInteger ;
	] ;
osdu:totalCostAmount rdf:type owl:DatatypeProperty ;
```
There are 413 matches for "owl:onProperty" and all are lowercased. I'd say more than 50% are wrong, eg all these:
```
    111:		owl:onProperty osdu:parameterkindid ;
    139:		owl:onProperty osdu:persistablereferencecrs ;
    205:		owl:onProperty osdu:datasetproperties ;
    216:		owl:onProperty osdu:facettypeid ;
    221:		owl:onProperty osdu:facetroleid ;
```

**Comment by ana-tudor** [comment]
Hi Vladimir - thanks for this important catch. We have corrected camelcasing usage, have fixed inconsistent naming in the restrictions, and have removed pluralization in property naming to the best of our abilities.
