### ISSUE TITLE
`boundingBoxEastBoundLongitude` etc are improperly defined

### ISSUE THREAD

**Issue by VladimirAlexiev** [Accenture/OSDU-Ontology#11]
```ttl
osdu:boundingBoxEastBoundLongitude rdf:type owl:DatatypeProperty ;
	rdfs:comment "Eastern longitude limit of the bounding box in degrees based on WGS 84 " ;
	rdfs:domain osdu:Extent ;
	rdfs:range gn:Feature ;
	owl:sameAs gn:longitude ;
```
Several mistakes here:
- the range should be `xsd:decimal` not `gn:Feature`. This is a data prop, whereas `gn:Feature` is a named GeoNames object
- Cannot be `owl:sameAs gn:longitude` because you're using this on 2 of your props, so they will become `owl:sameAs` between themselves. 
- Furthermore, you should use `equivalentProperty` or `subPropertyOf` for props (in this case I think you want to use the latter)

**Comment by ana-tudor** [comment]
Thanks for the catch - this has been addressed in our latest ontology commit, opting for rdfs:subPropertyOf

**Comment by VladimirAlexiev** [comment]
One more question related to `rdfs:subPropertyOf`: how is `osdu:Extent` related to `gn:Feature`?

`subPropertyOf` will cause every instance of `boundingBoxEastBoundLongitude` to be repeated as instance of `gn:longitude`.
But that prop is bound to a particular class. So eg if you have `rdfs:domain`, that will cause the original source node to get class  `gn:Feature`... which we want to be "compatible" with `osdu:Extent`
