### ISSUE TITLE
reduce the use of acronyms

### ISSUE THREAD

**Issue by VladimirAlexiev** [Accenture/OSDU-Ontology#12]
You use many abbreviations specific to O&G, eg
```ttl
cCLTopShotDistance rdf:type owl:DatatypeProperty ;
	rdfs:comment "Distance from CCL to Interval Top " ;
```
An internet search indicates this is "casing collar location" (or maybe "locator"?). IMHO it would be better to spell it out in full: `casingCollarLocationToTopShotDistance`.

In another case `casingCollarLocatorMD` you spell out "CCL" (which is inconsistent with the previous case), but abbreviate "measured depth". IMHO it would be better to spell it out in full: `casingCollarLocatorMeasuredDepth`.

**Comment by ana-tudor** [comment]
Hi Vladimir - in large part, we stick exactly to the acronyms, naming conventions, and descriptions provided for usage in the [OSDU 3.0.0 schema](https://community.opengroup.org/osdu/platform/data-flow/data-loading/open-test-data/-/tree/master/rc--3.0.0/3-schema). It would potentially be better to be more descriptive where possible, but we keep acronym usage the same to maximize exact matches for users trying to map relational OSDU data using this ontology.

**Comment by VladimirAlexiev** [comment]
I see what you mean, I found them at
- https://community.opengroup.org/osdu/platform/data-flow/data-loading/open-test-data/-/blob/master/rc--3.0.0/5-templates/master_data/template_maPerforationInterval.1.0.0.json#L486
- https://community.opengroup.org/osdu/platform/data-flow/data-loading/open-test-data/-/blob/master/rc--3.0.0/3-schema/master-data/PerforationInterval.1.0.0.json#L401

However, semantic modeling is largely about explicating the meaning of things.
So perhaps you can use the full spellings in rdfs:label to make things more clear?
```ttl
cCLTopShotDistance rdf:type owl:DatatypeProperty ;
  rdfs:label "Casing Collar Locator To Top Shot Distance";
  rdfs:comment "Distance from CCL to Interval Top " ;
``

**Comment by ana-tudor** [comment]
That is a good idea, I'll mark this as a desired fix and get to it when possible
