### ISSUE TITLE
improve the camel casing of abbreviations

### ISSUE THREAD

**Issue by VladimirAlexiev** [Accenture/OSDU-Ontology#13]
Even if you disagree with #12, IMHO it's better to treat abbreviations as "words" and then apply the camelCase convention. Eg
`cCLTopShotDistance` should become
`cclTopShotDistance` because it's easier to "parse out" the `ccl` part.

**Comment by ana-tudor** [comment]
Hi Vladimir - good point. These have been changed to the convention of having all letters in an acronym be lowercase when occuring at the beginning of a term, ie opting for "cclTopShotDistance" in your example above.
