### ISSUE TITLE
duplicated restrictions

### ISSUE THREAD

**Issue by VladimirAlexiev** [Accenture/OSDU-Ontology#15]
osdu:Point includes this restriction repeated 17 (!) times.
```
rdfs:subClassOf [
		a owl:Restriction ;
		owl:onProperty osdu:observationmeasureddepth ;
		owl:minCardinality "1"^^xsd:nonNegativeInteger ;
```
Repeating a restriction is pointless, so please diagnose what has caused this duplication. It's possible it occurs on other classes and restrictions as well

**Comment by ana-tudor** [comment]
As per Issue #2 , we have removed all duplicate restrictions - it was a small bug in the code.
