### ISSUE TITLE
unreadable description

### ISSUE THREAD

**Issue by VladimirAlexiev** [Accenture/OSDU-Ontology#3]
Several properties (osdu:workflowPersona, osdu:workflowUsage) have descriptions that do not parse:
```ttl
rdfs:comment "<...> that the record is technical assurance value is valid for. " ;
rdfs:comment "<...> that the record is technical assurance value is not valid for. " ;
```
Even the single comments don't parse properly.
The two comments put together are truly puzzling.

**Comment by ana-tudor** [comment]
Hi Vladimir, thanks for the catch. All comments have been consolidated and correct in our latest commit, to the best of our abilities.
