### ISSUE TITLE
unused properties

### ISSUE THREAD

**Issue by VladimirAlexiev** [Accenture/OSDU-Ontology#7]
`osdu:x, osdu:y` are defined but not used

**Comment by ana-tudor** [comment]
These properties have been renamed to osdu:xCoordinate and osdu:yCoordinate in our latest commit. Our OSDU ontology makes them available for use, ideally in combination with data conforming to the [OSDU 3.0.0 schema](https://community.opengroup.org/osdu/platform/data-flow/data-loading/open-test-data/-/tree/master/rc--3.0.0/3-schema). We believe it is not an issue that the properties are not directly used in the ontology.

**Comment by VladimirAlexiev** [comment]
But... what class can they be used with? Shouldn't there be a restriction to say they are used together??

**Comment by ana-tudor** [comment]
The classes they can be used with are specified via rdfs:domain (osdu:Point and osdu:AbstractCoordinates, in this case). We did not find it appropriate to include such a restriction, as in some real-world cases one value may be missing if data recorded for a pair of coordinates was incomplete.
