### ISSUE TITLE
rdfs:pattern doesn't exist

### ISSUE THREAD

**Issue by VladimirAlexiev** [Accenture/OSDU-Ontology#8]
In many data props you use `rdfs:pattern` to define a regex.
However, there is no such property. Instead, you should use:
- a data range definition with `owl:withRestrictions` and `xsd:pattern`, see https://www.w3.org/TR/owl2-quick-reference/#Data_Ranges
- OR a `sh:PropertyShape` with `sh:pattern`, see https://www.w3.org/TR/shacl/#PatternConstraintComponent

**Comment by VladimirAlexiev** [comment]
Furthermore, the patterns are over-quoted and too complicated. Eg:
```ttl
osdu:activityLevel rdf:type owl:DatatypeProperty ;
	rdfs:pattern "^[\\\\w\\\\-\\\\.]+:reference-data\\\\-\\\\-ActivityLevel:[\\\\w\\\\-\\\\.\\\\:\\\\%]+:[0-9]*$"
```
IMHO should become:
`"^[\\w.-]+:reference-data--ActivityLevel:[\\w.:%-]+:[0-9]*$"`

Dot has no special meaning in a char class `[...]` and putting the dash last removes its special meaning.

**Comment by ana-tudor** [comment]
The syntax used in the patterns is drawn from the OSDU 3.0.0 schema, and we conform exactly to values contained there, for interpretation by users of the OSDU schema. However, thank you for the catch on rdfs:pattern - we have changed our ontology to use xsd:pattern instead.

**Comment by VladimirAlexiev** [comment]
Ok, I agree about sticking to the original patterns as much as possible, even though they are grossly overquoted:
if the first dash is not quoted here, why the second and third should be?
`reference-data\\\\-\\\\-ActivityLevel`

But the patterns as rendered in Turtle are **incorrect** and will not work:
- `"^[\\\\w\\\\-\\\\.]"` uses backslashes in a Turtle string. When you reduce them, becomes
- `^[\\w\\-\\.]` as a regex pattern.
  - This means "any char except backslash, w, dot" and is obviously not what is wanted.
  - Backslash is mentioned 3 times, the last 2 times as a singleton range
  - What is wanted is `^[\w.-]` i.e. "any char except alphanumeric, dot or dash"

**Comment by VladimirAlexiev** [comment]
@ana-tudor 
- https://github.com/Accenture/OSDU-Ontology/blob/ef6fa990e71d2870c2aef19b2769dd85086a44d6/src/ttl_utils.py#L237 still mentions `rdfs:pattern`
- The regexps are still wrong, eg
```ttl
osdu:activityLevel rdf:type owl:DatatypeProperty ;
	xsd:pattern "^[\\\\w\\\\-\\\\.]+:reference-data\\\\-\\\\-ActivityLevel:[\\\\w\\\\-\\\\.\\\\:\\\\%]+:[0-9]*$" ;
```
